---
- name: Install FISH Shell
  apt:
    name: 
      - fish
      - curl
    state: present
    update_cache: yes

- name: Set FISH as default shell
  user:
    name: "{{ fish_user }}"
    shell: /usr/bin/fish
  when: fish_set_default

- name: Install Fisher
  command: fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
  become_user: "{{ fish_user }}"
  when: fisher_install

- name: Install Fisher Plugins
  command: fish -c "fisher install {{ item }}"
  with_items: "{{ fisher_plugins }}"
  become_user: "{{ fish_user }}"
  when: fisher_install

- name: Clone FISH Config Repo
  git:
    repo: "{{ fisher_config_repo }}"
    dest: "{{ fisher_config_path }}"
  become_user: "{{ fish_user }}"
  when: fisher_config_repo

- name: Download Starship Installer
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0700'
  when: starship_install

- name: Install Starship
  command: /tmp/starship_install.sh -y
  when: starship_install

- name: Clone Starship Config Repo
  git:
    repo: "{{ starship_config_repo }}"
    dest: "{{ starship_config_path }}"
  become_user: "{{ fish_user }}"
  when: starship_config_repo

- name: Init Starship
  command: starship init fish | source
  become_user: "{{ fish_user }}"
  when: 
    - starship_install
    - not starship_config_repo
